version: "3"
services:
  backdroppr:
    image: shinigandhi/backdroppr:latest
    restart: always
    volumes:
      - ./config:/config
      - /vault/Media/TV Shows:/tv
      - /vault/Media/Movies:/movies
