version: "3"
services:
  backdroppr:
    image: shinigandhi/backdroppr:latest
    restart: always
    volumes:
      - ./config:/config #Where the config file will be located
      - /vault/Media/TV Shows:/tv #TV show directory re-routing
      - /vault/Media/Movies:/movies #Movie directory re-routing
